models:
  - name: stg_orders
    columns:
      - name: taxed_price
        data_tests:
          - nonzero
  - name: stg_nations
    config:
      contract:
        enforced: true
      group: sales
    description: This is a table to store all nation information
    columns:
      - name: nation_id
        data_type: int
        constraints:
          - type: not_null
        description: This is the primary key for nations table
        data_tests:
          - unique
      - name: region_id
        data_type: number(4,0)
        data_tests:
          - relationships:
              arguments:
                to: ref('stg_regions')
                field: region_id 
              config:
                store_failures: true
                schema: Failures
      - name: name
        data_type: string
      - name: comment
        data_type: varchar(100)

  - name: stg_regions
    latest_version: 1
    versions:
      - v: 2
        config:
          materialized: table
          contract: {enforced: true}
        columns:
          - name: region_id
            description: This is the primary key
            data_type: int
          - name: name
            data_type: varchar
          # no comment column
      
      - v: 1
        config:
          materialized: table
          contract: {enforced: true}
        columns:
          - name: region_id
            description: This is the primary key
            data_type: int
          - name: name
            data_type: varchar
          - name: comment
            data_type: varchar
    
